// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9LqpSdXbUNRDRx05r4gBlaiSo0uKITU',
    appId: '1:1087009234026:web:96c70a834f4237f7d8fe13',
    messagingSenderId: '1087009234026',
    projectId: 'project-app1-50732',
    authDomain: 'project-app1-50732.firebaseapp.com',
    storageBucket: 'project-app1-50732.appspot.com',
    measurementId: 'G-SL2QZ0EK6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPyC746_0va3X18RhvtA7l55JG1vpMtY',
    appId: '1:1087009234026:android:83282962461385e6d8fe13',
    messagingSenderId: '1087009234026',
    projectId: 'project-app1-50732',
    storageBucket: 'project-app1-50732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0hIfSFEoPuGEBrsRbI36J70u4X2bC0I',
    appId: '1:1087009234026:ios:51d3f755fa755b7bd8fe13',
    messagingSenderId: '1087009234026',
    projectId: 'project-app1-50732',
    storageBucket: 'project-app1-50732.appspot.com',
    iosClientId:
        '1087009234026-fkrgkut3q9n0cmvnqa9qpesjmqmjinjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0hIfSFEoPuGEBrsRbI36J70u4X2bC0I',
    appId: '1:1087009234026:ios:51d3f755fa755b7bd8fe13',
    messagingSenderId: '1087009234026',
    projectId: 'project-app1-50732',
    storageBucket: 'project-app1-50732.appspot.com',
    iosClientId:
        '1087009234026-fkrgkut3q9n0cmvnqa9qpesjmqmjinjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );
}
